---
title: "Modelado de nichos ecológicos con procesos de puntos"
description: "Licenciatura en Manejo Sustentable de la Zona Costera"
author: "Gerardo Martín"
output:
   prettydoc::html_pretty:
      theme: hpstr
      highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introducción

## Perspectivas demográficas

1. [Ecología de poblaciones y nichos](13-Poblaciones-nichos-ecologicos.pdf)

    1.1. [Metapoblaciones sólo con K](Scripts-meta/Metapoblaciones.R)
    
    1.2. [Metapoblaciones con efecto Allee](Scripts-meta/Metapoblaciones-Allee.R)
    
2. [Modelo de "nicho" con datos de supervivencia](Caso-demografico.pdf)

    2.1. [Estimación de parámetros](https://gerardommc.github.io/Ecologia-Teorica-II/Modelo-Hev.html)
    
    2.2.  [Representación espacial del modelo de supervivencia](https://gerardommc.github.io/Ecologia-Teorica-II/Rep-esp-HeV.html)
    
    2.3. [Datos de Hendra virus](Datos-HeV.zip)
    
## Estimación de nichos con procesos de puntos

### Teorías

3. [Calibración](Calibracion.pdf)
4. [Análisis de presencias con patrones de puntos](Patrones-puntos.pdf)
5. [El proceso de modelación mediante patrones de puntos](Proceso-modelacion.pdf)
6. [Evaluación](9_Evaluacion-modelos.pptx)

### Tutoriales con `espatsmo` y `espuntnich`

6. [Repositorio de `espatsmo`](https://github.com/gerardommc/espatsmo)
7. [Repositorio de `espuntnich`](https://github.com/gerardommc/espuntnich)
8. Modelado de distribución con `espatsmo`

    8.1. [Las funciones básicas de `spatstat` mediante `espatsmo`](Ejemplo-lote.R)
    
    8.2. [Corrección de sesgo](Ejemplo-sesgo.R)
    
    8.3. [Control de autocorrelación espacial](Ejemplo-cluster.R)
    
9. Modelado de nichos ecológicos con `espuntnich`

    9.1. [Ejemplo de uso de variaciones de `ppmve`](Ejemplo-espuntnich.R)
    
10. [Evaluación de modelos con las funciones de `espatsmo`](Ejemplo-validacion.R)

### Aplicaciones

11. [Estimación de centroides con PPMs y MVE](14-Centroides-PPMs.pdf)

    11.1. [Tutorial](Tutorial-centroides.R)
    
    11.2. [Datos de presencia y ambientales](Datos-centroide.zip)
    
12. [Ecología de nichos en salud pública](Aplicaciones.pdf)


[Repositorio completo aquí](https://github.com/gerardommc/Curso-modelado-nichos)